### PR TITLE
Track clicked opt-in link on ft.com

### PR DESCRIPTION
**Pull request by keirog**

### CODE REVIEW

**Comment by commuterjoy** [comment]
how come?

**Comment by commuterjoy** [comment]
ijento is being replaced in ~3 months, we don't want to build up a dependency on it

**Comment by keirog** [comment]
@commuterjoy Ah ok, Chris M requested it due to difficulties joining FT.com and beacon data. Will catch up with you in person

**Comment by keirog** [comment]
Merging as discussed (ok to have it for the next few months; doesn't affect Next codebase)

**Pull request merged**
