### PR TITLE
Opt in view event

### PR DESCRIPTION
**Pull request by matthew-andrews**

### CODE REVIEW

**Comment by matthew-andrews** [comment]
is this ok, @commuterjoy

**Comment by commuterjoy** [comment]
As this is just a tracking pixel to count a page view from mDot we could just add o-tracking to the site.

<script type="application/json" data-o-tracking-config>
{
    "context": {
        "product": "m.ft.com"
    }
}
</script>
<script defer="" async="" src="https://build.origami.ft.com/bundles/js?modules=o-tracking%401.0.0"></script>

**Comment by commuterjoy** [comment]
Otherwise, ok to merge.

**Comment by matthew-andrews** [comment]
mdot gonna die soon :)

**Pull request merged**
