### PR TITLE
APP 12583: Use new promo text to suggest impending change

### PR DESCRIPTION
**Pull request by rowanbeentje**
@matthew-andrews could you do the honours and do any deploys/cache purging necessary?

https://jira.ft.com/browse/APP-12583 - date format is UK-centric but I suppose so are we :)

Haven't been able to try this locally due to origami registry being down but it's just a text change, in theory...

### CODE REVIEW

**Comment by rowanbeentje** [comment]
@wheresrhys Didn't realise Matt was still away!  Could you take a quick gander?

**Comment by matthew-andrews** [comment]
back now :sunglasses:

**Comment by matthew-andrews** [comment]
which product owner should i chat with about this?

**Comment by rowanbeentje** [comment]
I think this was requested by Gadi (see emails from yesterday); James Webb may be the man to talk to, I think he's provided us with the wording.

**Comment by matthew-andrews** [comment]
it's weird they asked you to do this but ok

**Pull request merged**
